name: Build USCIS DB
on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch: 

jobs:
  get_exit_node_ip:
    runs-on: ubuntu-latest
    outputs:
      TS_EXIT_NODE_IP: ${{ steps.get_exit_node_ip.outputs.TS_EXIT_NODE_IP }}
    steps:
    - name: Connect to stealthnet
      uses: tailscale/github-action@v3
      with:
        authkey: ${{ secrets.TS_AUTH_KEY }}
        tags: tag:ci-uscis
        statedir: /tmp/tailscale-state/
    - name: Get exit node IP
      id: get_exit_node_ip
      run: echo ::set-output name=TS_EXIT_NODE_IP::"$(dig +short ${{ secrets.TS_EXIT_NODE }})"
  build_db:
    runs-on: ubuntu-latest
    needs: get_exit_node_ip
    outputs:
      dbname: ${{ steps.dbname.outputs.dbname }}
    steps:
    - uses: actions/checkout@v4
    - name: Test pre-exit node
      run: curl 'https://api.ipify.org?format=json'
    - name: Connect to stealthnet (exit node)
      uses: tailscale/github-action@v3
      with:
        authkey: ${{ secrets.TS_AUTH_KEY }}
        args: '--exit-node=${{ needs.get_exit_node_ip.outputs.TS_EXIT_NODE_IP }}'
        tags: tag:ci-uscis
        statedir: /tmp/tailscale-state/
    - name: Test post-exit node
      run: curl 'https://api.ipify.org?format=json'
    - name: Download previous DB
      uses: robinraju/release-downloader@v1
      with:
        latest: true
        fileName: '*.db'
        out-file-path: 'prev'
    - name: Build DB and changelog
      run: ./build_db.sh
      env:
        SLOWMODE: 1
        STEALTH: 1
        STEALTH_ENDPOINT: ${{ secrets.STEALTH_ENDPOINT }}
        CURLSCRIPT_URL: ${{ secrets.CURLSCRIPT_URL }}
    - name: Get DB name
      id: dbname
      run: echo ::set-output name=dbname::"$(basename *.db .db)"
    - name: Upload DB
      uses: actions/upload-artifact@v4
      with:
        name: uscis-db
        path: '${{ steps.dbname.outputs.dbname }}.db'
        if-no-files-found: error
    - name: Upload changelog
      uses: actions/upload-artifact@v4
      with:
        name: changelog
        path: |
          changelog.txt
          sqldiff.txt
        if-no-files-found: error
    - name: Build JSON DB
      if: always()
      run: sqlite3 responses.db -A -c *.json
    - name: Upload JSON DB
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: responses-db
        path: 'responses.db'
        if-no-files-found: error
  publish_db:
    runs-on: ubuntu-latest
    needs: build_db
    steps:
      - name: Download DB
        uses: actions/download-artifact@v4
      - name: Create daily release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ needs.build_db.outputs.dbname }}
          tag_name: ${{ needs.build_db.outputs.dbname }}
          body_path: 'changelog/changelog.txt'
          files: 'uscis-db/*.db'
          fail_on_unmatched_files: true