name: Verify stealthnet fingerprints
on:
  workflow_dispatch: 

env:
  IPTEST_URL: ${{ vars.IPTEST_URL }}
  STEALTH_IPTEST_URL: ${{ secrets.STEALTH_IPTEST_URL }}

jobs:
  get_exit_node_ip:
    runs-on: ubuntu-latest
    outputs:
      TS_EXIT_NODE_IP: ${{ steps.get_exit_node_ip.outputs.TS_EXIT_NODE_IP }}
    steps:
    - name: Connect to stealthnet
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci-uscis
        version: latest
        use-cache: 'true'
    - name: Get exit node IP
      id: get_exit_node_ip
      run: echo "TS_EXIT_NODE_IP=$(dig +short ${{ secrets.TS_EXIT_NODE }})" >> $GITHUB_OUTPUT
    - name: Verify exit node set
      run: |
        if [ -z $"{TS_EXIT_NODE_IP}" ]; then
          exit 1
        fi
  get_direct_hash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install cURL scripts
      run: ./install_curl.sh
    - name: Show IP before Tailscale
      run: ./curl_request_api.sh ${{ env.IPTEST_URL }}
    - name: Connect to stealthnet
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci-uscis
        version: latest
        use-cache: 'true'
    - name: Show IP after Tailscale
      run: |
        timeout 30s bash -c "until ./curl_request_api.sh ${{ env.IPTEST_URL }}; do sleep 5; done"
        timeout 30s bash -c "until ./curl_request_api.sh ${{ env.STEALTH_IPTEST_URL }}; do sleep 5; done"
  get_tunneled_hash:
    runs-on: ubuntu-latest
    needs: get_exit_node_ip
    env:
      TS_EXIT_NODE_IP: ${{ needs.get_exit_node_ip.outputs.TS_EXIT_NODE_IP }}
    steps:
    - uses: actions/checkout@v4
    - name: Install cURL scripts
      run: ./install_curl.sh
    - name: Show IP before Tailscale
      run: ./curl_request_api.sh ${{ env.IPTEST_URL }}
    - name: Connect to stealthnet (exit node)
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        args: '--accept-dns=true --exit-node=${{ env.TS_EXIT_NODE_IP }}'
        tags: tag:ci-uscis
        version: latest
        use-cache: 'true'
    - name: Verify HTTP traffic is routed through exit node
      run: |
        echo "Available exit nodes:"
        tailscale status | grep 'exit node'
    - name: Show IP after Tailscale
      run: |
        timeout 30s bash -c "until ./curl_request_api.sh ${{ env.IPTEST_URL }}; do sleep 5; done"
        timeout 30s bash -c "until ./curl_request_api.sh ${{ env.STEALTH_IPTEST_URL }}; do sleep 5; done"
    - name: Disconnect stealthnet
      run: sudo tailscale down

